# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/polar
spring.datasource.username=postgres
spring.datasource.password=test

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
